# Generated by Django 2.2.10 on 2020-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200710_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
    ]
